name: CI Pipeline

on:
  push:
    branches: [ '**' ]           # На все пуши (включая main)
  pull_request:
    branches: [ main ]           # На PR в main

permissions:
  contents: read
  packages: write  # нужно для Docker push в GHCR

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest

  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: test         # Выполняется только если тесты прошли
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        id: vars
        run: |
          OWNER_LC=$(echo "${GITHUB_REPOSITORY%/*}" | tr '[:upper:]' '[:lower:]')
          echo "owner=${OWNER_LC}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.vars.outputs.owner }}/science-helper:latest
