name: tests-and-merge

on:
  push:

permissions:
  contents: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Установка зависимостей
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Прогон тестов
        run: pytest

  merge:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'  # Только если это не main
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Настройка Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Слияние в main
        run: |
          git fetch origin main
          git checkout main
          git merge ${{ github.ref_name }} --no-edit
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: [test, merge]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Owner in lowercase
        id: vars
        run: |
          OWNER_LC=$(echo "${GITHUB_REPOSITORY%/*}" | tr '[:upper:]' '[:lower:]')
          echo "owner=${OWNER_LC}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.vars.outputs.owner }}/science-helper:latest
